version: '3.9'

networks:
  macvlan:
    external: true
    name: macvlan

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    networks:
      macvlan:
        ipv4_address: 192.168.86.100
    ports:
      - "32400:32400"  # Explicitly open Plex’s main web interface port
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - VERSION=docker
    volumes:
      - /var/tmp/media:/media
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
